apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-rails-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ayushlohmod/K8-argoCD-files.git
    path: kubernnetes
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: my-rails-namespace

