apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dynamodb
spec:
  serviceName: "dynamodb"
  replicas: 1
  selector:
    matchLabels:
      app: dynamodb
  template:
    metadata:
      labels:
        app: dynamodb
    spec:
      containers:
      - name: dynamodb-container
        image: amazon/dynamodb-local:latest
        ports:
        - containerPort: 8000
        command: ["java", "-Djava.library.path=./DynamoDBLocal_lib", "-jar", "DynamoDBLocal.jar", "-sharedDb"]
        volumeMounts:
        - name: data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: ayush-storage-class 
      resources:
        requests:
          storage: 1Gi

