apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails-app
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: rails-app
  template:
    metadata:
      labels:
        app: rails-app
    spec:
      containers:
      - name: rails-app-container
        image: ayush-rail-app-container
        ports:
        - containerPort: 3000
        
